name: Semantic Version Manager
description: Handles the semantic versioning tags for a repository

branding:
  icon: check-square
  color: blue

inputs:
  manifest-path:
    description:
      The path to the manifest file that contains the version information,
      relative to the root of the repository. If not set, then `version` should
      be set to an explicit version in SemVer 2.0 format.
    required: false
  overwrite:
    default: 'false'
    description:
      If tags already exist for the specified or inferred version, setting this
      to 'true' will overwrite them. Defaults to 'false'.
    required: false
  ref:
    default: ${{ github.base_ref }}
    description:
      The Git ref to tag with the specified or inferred version. This defaults
      to the base ref of a pull request event trigger.
    required: false
  use-version:
    description:
      The version you want to explicitly use (e.g. '1.2.3-beta.4+build.5'). This
      must follow SemVer standards. If not set, then `manifest-path` should be
      set so the action can attempt to infer the version from the contents of
      the repository.
    required: false
  workspace:
    default: ${{ github.workspace }}
    description:
      The path where the repository has been cloned using the `actions/checkout`
      step. If not set, then `version` should be set to an explicit version.
    required: false

outputs:
  major-minor-patch:
    description: The major, minor, and patch versions (e.g. `1.2.3`)
  major-minor:
    description: The major and minor versions (e.g. `1.2`)
  major:
    description: The major version (e.g. `1` for `1.2.3`)
  minor:
    description: The minor version (e.g. `2` for `1.2.3`)
  patch:
    description: The patch version (e.g. `3` for `1.2.3`)
  prerelease:
    description: The prerelease version (e.g. `alpha.4`)
  version:
    description: The full semantic version (e.g. `1.2.3-alpha.4`)

runs:
  using: node20
  main: dist/index.js
